import Navbar from "@/components/Navbar";
import SignupCard from "@/components/Signup/SignupCard";
import Background from "@/components/background";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "สมัครสมาชิก | Xammy",
    description: "Generated by create next app",
};

export default function SignInPage() {
    return (
        <div className="relative min-h-screen flex items-center justify-center">
            <Background />
            <Navbar />
            <div className="relative z-10">
                <SignupCard />
            </div>
        </div>
    );
}
